name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true
  reply-to-issues:
    description: ''
    default: 'true'
    required: false
  reply-to-prs:
    description: ''
    default: 'true'
    required: false
  message-issue:
    description: ''
    default: 'this is a message issue'
    required: false
  message-pr:
    description: ''
    default: 'this is a messsage PR'
    required: false
  external-contributor-label:
    description: ''
    default: 'community'
    required: false
  pr-assignee-from-issue:
    description: ''
    default: ''
    required: false
  warn-missing-issue:
    description: ''
    default: 'false'
    required: false
  missing-issue-message:
    description: ''
    default: 'missing linked issue'
    required: false
# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
